### PR TITLE
Claim io.kevinlee sbt-devoops

### PR DESCRIPTION
**Pull request by Kevin-Lee**
It's published here.
https://bintray.com/sbt/sbt-plugin-releases?filterByPkgName=sbt-devoops

GitHub: https://github.com/Kevin-Lee/sbt-devoops

### CODE REVIEW

**Comment by Kevin-Lee** [comment]
I still don't see it in Scaladex. Have I done anything wrong? Should my GitHub username in the `claims.json` file all lower cases?

**Comment by julienrf** [comment]
I think that part is correct.

I see that your project is not part of the scaladex source of data, and I don’t know why. https://github.com/scalacenter/scaladex/issues/580 might be the reason.

**Comment by Kevin-Lee** [comment]
@julienrf OK, I'll make them lower cases. Thanks for your answer!

**Comment by Kevin-Lee** [comment]
@julienrf Ah... OK, sorry I somehow hadn't seen that link before I created another PR. I hope that will be fixed soon. Thanks!

**Comment by Kevin-Lee** [comment]
But to check if the upper case is an issue or not could you please merge the other PR I created?
https://github.com/scalacenter/scaladex-contrib/pull/54

**Pull request merged**
