### PR TITLE
java libs

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by ktoso** [comment]
Just to know what to expect, this will get deployed indexed automtically from here on?

(Not visible yet: https://index.scala-lang.org/search?q=typesafehub%2Fconfig I guess it takes time to reindex - is it a nightly thing?)

**Comment by MasseGuillaume** [comment]
@ktoso I had some issues running the index. I have to prepare for my demo at Scala eXchange. I will take a look at it as soon as possible.

**Comment by ktoso** [comment]
Oh, ok - forgot it's scalax time :) Enjoy.
Just wanted to know what to expect in terms of timing - technically it's automatic if we add a project here or we need to ping you?

No worries, this is not urgent 👍

**Comment by MasseGuillaume** [comment]
it should update daily ;-)

**Pull request merged**
