### PR TITLE
Add ocaps to claim

### PR DESCRIPTION
**Pull request by wsargent**
I think this is right -- I don't see a "how to add your project to scaladex" page anywhere.

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
@wsargent the bintray indexing is disabled currently. This is why your library is not showing up,

**Comment by wsargent** [comment]
@MasseGuillaume This is closed with unmerged commits and https://github.com/scalacenter/scaladex-contrib/blob/master/claims.json does not show ocaps merged in another PR.  Did you mean to do this?

**Comment by wsargent** [comment]
@MasseGuillaume ping

**Comment by MasseGuillaume** [comment]
@wsargent re-indexing Bintay now.

**Comment by wsargent** [comment]
@MasseGuillaume ty

**Pull request merged**
